version: '3'
services:
  producer_app: &producer
    build:
      context: .
      dockerfile: DockerFiles/Python/dockerfile
    environment:
      - "PYTHONUNBUFFERED=1"
    volumes:
      - .:/Producer_Consumer
    ports:
      - 8000:8000
    depends_on:
      - rabbitmq
      - celery-worker
      - celery-beat
  rabbitmq:
    image: rabbitmq:3.7.26
  celery-worker: &celery-worker
    <<: *producer
    command: celery -A Producer_Consumer worker --loglevel=info --concurrency=2
    ports: []
    depends_on:
      - rabbitmq
  celery-beat:
    <<: *celery-worker
    command: celery beat -A Producer_Consumer --loglevel=info --pidfile=/dev/shm/celery_beat.pid
    ports: []
    depends_on:
      - celery-worker